{ config, lib, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ./config/starship/starship.nix
];

  boot.loader.grub.enable = true;
  boot.loader.grub.device = "nodev";
  boot.loader.grub.efiSupport = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub.useOSProber = true;
  
  networking.hostName = "howard";
  networking.firewall.enable = true;
  networking.firewall.allowedTCPPorts = [ 22 ];
  networking.firewall.allowedUDPPorts = [ 51820 ]; # Tailscale

  # Static IP configuration
  systemd.network = {
    enable = true;
    networks."10-eth0" = {
      matchConfig.Name = "enp1s0";
      networkConfig = {
        Address = [ "192.168.1.10/24" ];
        Gateway = "192.168.1.1";
        DNS = [ "192.168.1.1" "1.1.1.1" "8.8.8.8" ];
      };
    };
  };


  # Disable DHCP since we're using static IP with systemd.network
  networking.useDHCP = false;
  networking.useNetworkd = true;
  # SSH server configuration
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "yes";
      PasswordAuthentication = true;
      KbdInteractiveAuthentication = false;
    };
    # Allow root SSH with key only
    extraConfig = ''
      Match User root
        PermitRootLogin yes
        PubkeyAuthentication yes
        PasswordAuthentication yes 
    '';
  };

  # Tailscale - FIXED: use extraUpFlags instead of settings
  services.tailscale = {
    enable = true;
    extraUpFlags = [
      "--accept-dns=true"
      "--accept-routes=true"
    ];
  };

  # User configuration
  users.users.ali = {
    isNormalUser = true;
    description = "Ali";
    extraGroups = [ "wheel" "networkmanager" ];
    openssh.authorizedKeys.keyFiles = [ /home/ali/system-config/hosts/howard/keys ];
  };

  users.users.root = {
    openssh.authorizedKeys.keyFiles = [ /home/ali/system-config/hosts/howard/keys ];
 };

  users.users.root.shell = pkgs.zsh;
  users.users.ali.shell = pkgs.zsh

  # Environment
  environment = {
    shellInit = ''
      eval "$(direnv hook zsh)"
    '';
    variables = {
      EDITOR = "nvim";
    };
  };



  # Packages
  environment.systemPackages = with pkgs; [
    # Core utils
    git
    curl
    wget
    htop
    tmux
    tree

    # Shell enhancements
    zsh
    starship
    direnv
    eza

    # Editor
    neovim

    # System info
    fastfetch
    neofetch

    # Networking
    iputils
    iproute2
    tcpdump
    nmap
    nettools

    # Compression
    unzip
    zip
    coreutils
    gzip
    bzip2
    xz

    # Build tools
    gcc
    gnumake
    cmake
    pkg-config

    # GitHub CLI
    gh

    # Tailscale (should auto-install via service, but ensuring package)
    tailscale
  ];

  # Enable zsh globally - FIXED: This was missing and causing the error
  programs.zsh.enable = true;

  # Configure zsh as default shell for user
  users.defaultUserShell = pkgs.zsh;

  # System state version - FIXED: Added to suppress warning
  system.stateVersion = "24.11";

  # Timezone
  time.timeZone = "America/New_York";

  # Locale
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_TIME = "en_US.UTF-8";
  };

  # Console font
  console.font = "Lat15-Fixed16";

  # Nix configuration
  nix = {
    package = pkgs.nix;
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 7d";
    };
  };

  # Systemd tmpfiles
  systemd.tmpfiles.rules = [
    "d /tmp 1777 root root -"
  ];

  # Automatic upgrades (optional - disabled by default)
  # system.autoUpgrade.enable = true;
  # system.autoUpgrade.flags = [ "--flake" ".#howard" ];

  # Power management
  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
    };
  };

  # Firmware updates
  services.fwupd.enable = true;

  # Sudo configuration
  security.sudo.wheelNeedsPassword = false;

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # Generate hardware-configuration.nix on first install
  # This will be auto-generated by nixos-install
}
